//
//  ESISceneConstants.h
//  GLES Introduction Example
//
//  Created by Blake Harrison on 2/26/14.
//  Copyright (c) 2014 Blake Harrison. All rights reserved.
//

#ifndef GLES_Introduction_Example_ESISceneConstants_h
#define GLES_Introduction_Example_ESISceneConstants_h
#define PI 3.141592653
#define RADIANS_TO_DEGREES 180 / PI
enum uniformIndex
{
    MODELVIEWPROJECTION_MATRIX_UNIFORM,
    NORMAL_MATRIX_UNIFORM,
    MODELVIEW_MATRIX_UNIFORM,
    MATERIAL_AMBIENT_UNIFORM,
    MATERIAL_DIFFUSE_UNIFORM,
    MATERIAL_SPECULAR_UNIFORM,
    MATERIAL_SPECULAR_EXP_UNIFORM,
    NUMBER_OF_LIGHTS_UNIFORM,
    LIGHT_SCENE_AMBIENT_INTENSITY_UNIFORM,
    
    LIGHT0_POSITION_UNIFORM,
    LIGHT0_DIFFUSE_INTENSITY_UNIFORM,
    LIGHT0_SPECULAR_INTENSITY_UNIFORM,
    
    LIGHT1_POSITION_UNIFORM,
    LIGHT1_DIFFUSE_INTENSITY_UNIFORM,
    LIGHT1_SPECULAR_INTENSITY_UNIFORM,
    
    LIGHT2_POSITION_UNIFORM,
    LIGHT2_DIFFUSE_INTENSITY_UNIFORM,
    LIGHT2_SPECULAR_INTENSITY_UNIFORM,
    
    LIGHT3_POSITION_UNIFORM,
    LIGHT3_DIFFUSE_INTENSITY_UNIFORM,
    LIGHT3_SPECULAR_INTENSITY_UNIFORM,
    
    LIGHT4_POSITION_UNIFORM,
    LIGHT4_DIFFUSE_INTENSITY_UNIFORM,
    LIGHT4_SPECULAR_INTENSITY_UNIFORM,
    NUMBER_OF_UNIFORMS
};

enum attributeIndex
{
    VERTEX_POS_ATTRIB,
    VERTEX_COLOR_ATTRIB,
    VERTEX_INDICES_ATTRIB,
    VERTEX_NORMAL_ATTRIB,
    NUMBER_OF_ATTRIBUTES
};

enum vetexArrayBufferIndex
{
    VERTEX_ARRAY_BUFFER_OBJECT_0,
    NUMBER_OF_VERTEX_ARRAY_OBJECTS
};

typedef enum {
    none,
    released,
    moving
} ESITouchMovementState;

#endif
